In [1]:
def rating (value):
    if value <= 2:
        return 'низкий рейтинг'
    elif value <= 4:
        return 'средний рейтинг'
    elif 4.5 <= value <= 5:
        return 'высокий рейтинг'
    return 'неправильные данные рейтинга'

In [4]:
import pandas as pd

file_ratings = pd.read_csv('/Users/macbook_bd/Downloads/ml-latest-small/ratings.csv')
file_movies = pd.read_csv('/Users/macbook_bd/Downloads/ml-latest-small/movies.csv')
common_file = pd.merge(file_movies, file_ratings, on='movieId', how='outer')
common_file['class'] = common_file['rating'].apply(rating)
common_file.groupby('class').count().reset_index()

,class,movieId,title,genres,userId,rating,timestamp
0,высокий рейтинг,22818,22818,22818,22818,22818,22818
1,неправильные данные рейтинга,59,59,59,0,0,0
2,низкий рейтинг,13385,13385,13385,13385,13385,13385
3,средний рейтинг,63801,63801,63801,63801,63801,63801

In [82]:
geo_data = {'Центр': ['москва', 'тула', 'ярославль'],
'Северо-Запад': ['петербург', 'псков', 'мурманск'],
'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']
}

def region (value):
    value.lower()
    for sep_value in value.split():
        if sep_value in geo_data['Центр']:
            return 'Центр' 
        if sep_value in geo_data['Северо-Запад']:
            return 'Северо-Запад' 
        if sep_value in geo_data['Дальний Восток']:
            return 'Дальний Восток' 
    return 'undenied'

In [83]:
import pandas as pd

file_keywords = pd.read_csv('/Users/macbook_bd/Downloads/ml-latest-small/keywords.csv')
file_keywords['regions'] = file_keywords['keyword'].apply(region)

In [84]:
file_keywords.groupby('regions').count().reset_index()

          regions  keyword  shows
0        undenied    99406  99406
1  Дальний Восток       64     64
2    Северо-Запад      146    146
3           Центр      384    384